name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
          
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore packages
      run: nuget restore Certify.sln    
      
    - name: Build solution
      run:  msbuild Certify.sln -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Certify
        path: Certify\Certify\bin\Release\Certify.exe
